export type CountryReturnVisit = "Y" | "N" | "M";

export type CountryRatingRow = {
  name: string;
  continent: string;
  culture: number;
  entertainment: number;
  landscapes: number;
  price: number;
  easeOfEntry: number;
  food: number;
  experiences: number;
  drivers: number | null;
  roads: number | null;
  rating: number | null;
  returnVisit: CountryReturnVisit | null;
  reason: string;
};

export type CountryRatingScores = Pick<
  CountryRatingRow,
  | "culture"
  | "entertainment"
  | "landscapes"
  | "price"
  | "easeOfEntry"
  | "food"
  | "experiences"
  | "drivers"
  | "roads"
>;

/**
 * Overall rating = mean of category scores.
 * Drivers/roads are included only when set.
 */
export function computeCountryRatingAverage(
  scores: CountryRatingScores,
): number | null {
  const values = [
    scores.culture,
    scores.entertainment,
    scores.landscapes,
    scores.price,
    scores.easeOfEntry,
    scores.food,
    scores.experiences,
    scores.drivers,
    scores.roads,
  ].filter((value): value is number => value != null && Number.isFinite(value));

  if (values.length === 0) return null;
  return values.reduce((sum, value) => sum + value, 0) / values.length;
}

/** Personal country ratings seed data from the Country Ratings spreadsheet. */
export const COUNTRY_RATING_SEED: CountryRatingRow[] = [
  {
    name: "Kosovo",
    continent: "Balkan Europe",
    culture: 3,
    entertainment: 7,
    landscapes: 2,
    price: 4,
    easeOfEntry: 10,
    food: 5,
    experiences: 8,
    drivers: 5,
    roads: 5,
    rating: 5.444444444,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Albania",
    continent: "Balkan Europe",
    culture: 6,
    entertainment: 4,
    landscapes: 5,
    price: 7,
    easeOfEntry: 10,
    food: 5,
    experiences: 3,
    drivers: null,
    roads: null,
    rating: 5.714285714,
    returnVisit: "M",
    reason: "",
  },
  {
    name: "Bosnia",
    continent: "Balkan Europe",
    culture: 6,
    entertainment: 3,
    landscapes: 4,
    price: 7,
    easeOfEntry: 10,
    food: 5,
    experiences: 6,
    drivers: null,
    roads: null,
    rating: 5.857142857,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Croatia",
    continent: "Balkan Europe",
    culture: 7,
    entertainment: 7,
    landscapes: 6.5,
    price: 4,
    easeOfEntry: 10,
    food: 5,
    experiences: 4,
    drivers: null,
    roads: null,
    rating: 6.214285714,
    returnVisit: "M",
    reason: "",
  },
  {
    name: "Serbia",
    continent: "Balkan Europe",
    culture: 7,
    entertainment: 7,
    landscapes: 4,
    price: 7,
    easeOfEntry: 10,
    food: 5,
    experiences: 5,
    drivers: 6,
    roads: 6,
    rating: 6.333333333,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Macedonia",
    continent: "Balkan Europe",
    culture: 6,
    entertainment: 8,
    landscapes: 5,
    price: 7,
    easeOfEntry: 10,
    food: 5,
    experiences: 9,
    drivers: null,
    roads: null,
    rating: 7.142857143,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Montenegro",
    continent: "Balkan Europe",
    culture: 7,
    entertainment: 7,
    landscapes: 7,
    price: 7,
    easeOfEntry: 10,
    food: 5,
    experiences: 7,
    drivers: null,
    roads: null,
    rating: 7.142857143,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "St Kitts and Nevis",
    continent: "Carribean",
    culture: 2,
    entertainment: 2,
    landscapes: 3,
    price: 3,
    easeOfEntry: 9,
    food: 5,
    experiences: 1,
    drivers: null,
    roads: null,
    rating: 3.571428571,
    returnVisit: "N",
    reason: "Was sick",
  },
  {
    name: "Puerto Rico",
    continent: "Carribean",
    culture: 4,
    entertainment: 6,
    landscapes: 5,
    price: 4,
    easeOfEntry: 5,
    food: 5,
    experiences: 2,
    drivers: null,
    roads: null,
    rating: 4.428571429,
    returnVisit: "M",
    reason: "",
  },
  {
    name: "Barbados",
    continent: "Carribean",
    culture: 2,
    entertainment: 3,
    landscapes: 3,
    price: 5,
    easeOfEntry: 10,
    food: 5,
    experiences: 3,
    drivers: 4,
    roads: 5,
    rating: 4.444444444,
    returnVisit: "N",
    reason: "Bit dull, flat, English. Nothing happene",
  },
  {
    name: "Martinique",
    continent: "Carribean",
    culture: 2,
    entertainment: 5,
    landscapes: 5,
    price: 3,
    easeOfEntry: 10,
    food: 5,
    experiences: 5,
    drivers: 5,
    roads: 5,
    rating: null,
    returnVisit: "M",
    reason: "",
  },
  {
    name: "Haiti",
    continent: "Carribean",
    culture: 6,
    entertainment: 2,
    landscapes: 6,
    price: 6,
    easeOfEntry: 9,
    food: 5,
    experiences: 5,
    drivers: null,
    roads: null,
    rating: 5.571428571,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "St Lucia",
    continent: "Carribean",
    culture: 2,
    entertainment: 3,
    landscapes: 7.5,
    price: 6,
    easeOfEntry: 10,
    food: 5,
    experiences: 7,
    drivers: 5,
    roads: 5,
    rating: 5.611111111,
    returnVisit: "Y",
    reason: "Pitons and hike were great",
  },
  {
    name: "St Vincent",
    continent: "Carribean",
    culture: 4,
    entertainment: 3,
    landscapes: 6.5,
    price: 6,
    easeOfEntry: 10,
    food: 5,
    experiences: 7,
    drivers: 5,
    roads: 5,
    rating: 5.722222222,
    returnVisit: "Y",
    reason: "Every island had a different vibe, I lov",
  },
  {
    name: "Dominica",
    continent: "Carribean",
    culture: 4,
    entertainment: 2,
    landscapes: 7.5,
    price: 7,
    easeOfEntry: 10,
    food: 5,
    experiences: 6,
    drivers: 5,
    roads: null,
    rating: 5.8125,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Dominican Republic",
    continent: "Carribean",
    culture: 6,
    entertainment: 6,
    landscapes: 5,
    price: 6,
    easeOfEntry: 9,
    food: 5,
    experiences: 4,
    drivers: null,
    roads: null,
    rating: 5.857142857,
    returnVisit: "M",
    reason: "",
  },
  {
    name: "Antigua",
    continent: "Carribean",
    culture: 4,
    entertainment: 6,
    landscapes: 4,
    price: 6,
    easeOfEntry: 9,
    food: 5,
    experiences: 8,
    drivers: 5,
    roads: null,
    rating: 5.875,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Grenada",
    continent: "Carribean",
    culture: 7,
    entertainment: 6,
    landscapes: 6.5,
    price: 6,
    easeOfEntry: 10,
    food: 5,
    experiences: 7,
    drivers: 5,
    roads: 5,
    rating: 6.388888889,
    returnVisit: "N",
    reason: "Great time here, great spot for the old",
  },
  {
    name: "Trinidad",
    continent: "Carribean",
    culture: 7,
    entertainment: 7,
    landscapes: 6,
    price: 7,
    easeOfEntry: 10,
    food: 6,
    experiences: 7,
    drivers: 5,
    roads: 5,
    rating: 6.666666667,
    returnVisit: "N",
    reason: "Had a class time couchsurfing, and h",
  },
  {
    name: "Honduras",
    continent: "Central America",
    culture: 3,
    entertainment: 3,
    landscapes: 3,
    price: 7,
    easeOfEntry: 10,
    food: 4,
    experiences: 1,
    drivers: null,
    roads: null,
    rating: 4.428571429,
    returnVisit: "Y",
    reason: "Not there long enough to see it",
  },
  {
    name: "Guatemala",
    continent: "Central America",
    culture: 7,
    entertainment: 4,
    landscapes: 7,
    price: 8,
    easeOfEntry: 10,
    food: 4,
    experiences: 8,
    drivers: null,
    roads: null,
    rating: 6.857142857,
    returnVisit: "Y",
    reason: "Cool, full of unexpected bits",
  },
  {
    name: "Turkmenistan",
    continent: "Central Asia",
    culture: 6,
    entertainment: 3,
    landscapes: 3,
    price: 2,
    easeOfEntry: 1,
    food: 4,
    experiences: 3,
    drivers: 6,
    roads: 3,
    rating: 3.444444444,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Uzbekistan",
    continent: "Central Asia",
    culture: 9,
    entertainment: 4,
    landscapes: 3,
    price: 5,
    easeOfEntry: 3,
    food: 4,
    experiences: 4,
    drivers: 1,
    roads: 4,
    rating: 4.111111111,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Tajikistan",
    continent: "Central Asia",
    culture: 5,
    entertainment: 4,
    landscapes: 6,
    price: 6,
    easeOfEntry: 5,
    food: 5,
    experiences: 5,
    drivers: 5,
    roads: 4,
    rating: 5,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Iran",
    continent: "Central Asia",
    culture: 9,
    entertainment: 5,
    landscapes: 6,
    price: 10,
    easeOfEntry: 1,
    food: 6,
    experiences: 9,
    drivers: 5,
    roads: 5,
    rating: 6.222222222,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Kyrgyzstan",
    continent: "Central Asia",
    culture: 5,
    entertainment: 5,
    landscapes: 9,
    price: 6,
    easeOfEntry: 10,
    food: 5,
    experiences: 7,
    drivers: 7,
    roads: 6,
    rating: 6.666666667,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Kazakhstan",
    continent: "Central Asia",
    culture: 4,
    entertainment: 6,
    landscapes: 8,
    price: 6,
    easeOfEntry: 10,
    food: 6,
    experiences: 7,
    drivers: 7,
    roads: 7,
    rating: 6.777777778,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Liechenstein",
    continent: "Central Europe",
    culture: 7,
    entertainment: 1,
    landscapes: 5,
    price: 1,
    easeOfEntry: 10,
    food: 5,
    experiences: 2,
    drivers: null,
    roads: null,
    rating: 4.428571429,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Slovakia",
    continent: "Central Europe",
    culture: 5,
    entertainment: 5,
    landscapes: 7.5,
    price: 4,
    easeOfEntry: 10,
    food: 5,
    experiences: 4,
    drivers: null,
    roads: null,
    rating: 5.785714286,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Switzerland",
    continent: "Central Europe",
    culture: 8,
    entertainment: 5,
    landscapes: 7,
    price: 1,
    easeOfEntry: 10,
    food: 5,
    experiences: 3,
    drivers: 8,
    roads: 8,
    rating: 6.111111111,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Czechia",
    continent: "Central Europe",
    culture: 7.5,
    entertainment: 7,
    landscapes: 5,
    price: 4,
    easeOfEntry: 10,
    food: 5,
    experiences: 5,
    drivers: null,
    roads: null,
    rating: 6.214285714,
    returnVisit: "M",
    reason: "",
  },
  {
    name: "Slovenia",
    continent: "Central Europe",
    culture: 6,
    entertainment: 7,
    landscapes: 6,
    price: 5,
    easeOfEntry: 10,
    food: 5,
    experiences: 6,
    drivers: null,
    roads: null,
    rating: 6.428571429,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Hungary",
    continent: "Central Europe",
    culture: 7.5,
    entertainment: 8,
    landscapes: 3,
    price: 4,
    easeOfEntry: 10,
    food: 5,
    experiences: 7,
    drivers: 7,
    roads: 7,
    rating: 6.5,
    returnVisit: "M",
    reason: "",
  },
  {
    name: "Austria",
    continent: "Central Europe",
    culture: 8,
    entertainment: 6,
    landscapes: 7,
    price: 3,
    easeOfEntry: 10,
    food: 5,
    experiences: 5,
    drivers: 8,
    roads: 8,
    rating: 6.666666667,
    returnVisit: "M",
    reason: "",
  },
  {
    name: "Germany",
    continent: "Central Europe",
    culture: 8,
    entertainment: 8,
    landscapes: 6,
    price: 4,
    easeOfEntry: 10,
    food: 5,
    experiences: 8,
    drivers: 8,
    roads: 6,
    rating: 7,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Somaliland",
    continent: "East Africa",
    culture: 2,
    entertainment: 1,
    landscapes: 1,
    price: 5,
    easeOfEntry: 2,
    food: 4,
    experiences: 2,
    drivers: 5,
    roads: 5,
    rating: 3,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Djibouti",
    continent: "East Africa",
    culture: 2,
    entertainment: 1,
    landscapes: 4,
    price: 4,
    easeOfEntry: 5,
    food: 4,
    experiences: 3,
    drivers: 5,
    roads: 5,
    rating: 3.666666667,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Ethiopia",
    continent: "East Africa",
    culture: 7,
    entertainment: 5,
    landscapes: 7,
    price: 7,
    easeOfEntry: 4,
    food: 6,
    experiences: 5,
    drivers: 4,
    roads: 4,
    rating: 5.444444444,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "China",
    continent: "East Asia",
    culture: 10,
    entertainment: 5,
    landscapes: 10,
    price: 7,
    easeOfEntry: 8,
    food: 8,
    experiences: 9,
    drivers: 3,
    roads: 9,
    rating: 7.666666667,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Taiwan",
    continent: "East Asia",
    culture: 6,
    entertainment: 5,
    landscapes: 6,
    price: 5,
    easeOfEntry: 9,
    food: 6,
    experiences: 3,
    drivers: null,
    roads: null,
    rating: 5.714285714,
    returnVisit: "N",
    reason: "Was recovering for most of it, buses",
  },
  {
    name: "South Korea",
    continent: "East Asia",
    culture: 7,
    entertainment: 6,
    landscapes: 6,
    price: 5,
    easeOfEntry: 9,
    food: 7,
    experiences: 7,
    drivers: null,
    roads: null,
    rating: 6.714285714,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Japan",
    continent: "East Asia",
    culture: 10,
    entertainment: 7,
    landscapes: 8,
    price: 5,
    easeOfEntry: 10,
    food: 8,
    experiences: 7,
    drivers: 9,
    roads: 9,
    rating: 8.111111111,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Lithuania",
    continent: "Eastern Europe",
    culture: 5,
    entertainment: 6,
    landscapes: 4,
    price: 5,
    easeOfEntry: 10,
    food: 5,
    experiences: 4,
    drivers: null,
    roads: null,
    rating: 5.571428571,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Transnistria",
    continent: "Eastern Europe",
    culture: 4,
    entertainment: 3,
    landscapes: 1,
    price: 6,
    easeOfEntry: 10,
    food: 5,
    experiences: 4,
    drivers: null,
    roads: null,
    rating: 4.714285714,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Moldova",
    continent: "Eastern Europe",
    culture: 3,
    entertainment: 5,
    landscapes: 3,
    price: 5,
    easeOfEntry: 10,
    food: 5,
    experiences: 3,
    drivers: null,
    roads: null,
    rating: 4.857142857,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Bulgaria",
    continent: "Eastern Europe",
    culture: 4,
    entertainment: 5,
    landscapes: 3,
    price: 5,
    easeOfEntry: 10,
    food: 5,
    experiences: 4,
    drivers: null,
    roads: null,
    rating: 5.142857143,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Russia",
    continent: "Eastern Europe",
    culture: 8,
    entertainment: 3,
    landscapes: 6,
    price: 4,
    easeOfEntry: 2,
    food: 6,
    experiences: 5,
    drivers: 7,
    roads: 8,
    rating: 5.444444444,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Latvia",
    continent: "Eastern Europe",
    culture: 5,
    entertainment: 7,
    landscapes: 3,
    price: 5,
    easeOfEntry: 10,
    food: 5,
    experiences: 5,
    drivers: null,
    roads: null,
    rating: 5.714285714,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Romania",
    continent: "Eastern Europe",
    culture: 6,
    entertainment: 7,
    landscapes: 7.5,
    price: 4,
    easeOfEntry: 10,
    food: 6,
    experiences: 6.5,
    drivers: 6,
    roads: 7,
    rating: 6.666666667,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Poland",
    continent: "Eastern Europe",
    culture: 8,
    entertainment: 8,
    landscapes: 6,
    price: 4,
    easeOfEntry: 10,
    food: 5,
    experiences: 6,
    drivers: null,
    roads: null,
    rating: 6.714285714,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Ukraine",
    continent: "Eastern Europe",
    culture: 8,
    entertainment: 8,
    landscapes: 6,
    price: 7,
    easeOfEntry: 10,
    food: 5,
    experiences: 9,
    drivers: null,
    roads: null,
    rating: 7.571428571,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "United Arab Emirites",
    continent: "Middle East",
    culture: 2,
    entertainment: 2,
    landscapes: 2,
    price: 3,
    easeOfEntry: 8,
    food: 3,
    experiences: 3,
    drivers: 4,
    roads: 7,
    rating: 3.777777778,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Egypt",
    continent: "North Africa",
    culture: 8,
    entertainment: 5,
    landscapes: 5,
    price: 5,
    easeOfEntry: 5,
    food: 5,
    experiences: 7,
    drivers: 2,
    roads: 5,
    rating: 5.222222222,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Algeria",
    continent: "North Africa",
    culture: 8,
    entertainment: 4,
    landscapes: 7.5,
    price: 9,
    easeOfEntry: 2,
    food: 5,
    experiences: 6,
    drivers: 4,
    roads: 6,
    rating: 5.722222222,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Tunisia",
    continent: "North Africa",
    culture: 7.5,
    entertainment: 2,
    landscapes: 6,
    price: 6,
    easeOfEntry: 10,
    food: 5,
    experiences: 7,
    drivers: 3,
    roads: 5,
    rating: 5.722222222,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Morocco",
    continent: "North Africa",
    culture: 7,
    entertainment: 3,
    landscapes: 7.5,
    price: 7,
    easeOfEntry: 7,
    food: 6,
    experiences: 7,
    drivers: 4,
    roads: 6,
    rating: 6.055555556,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "USA",
    continent: "North America",
    culture: 5,
    entertainment: 6,
    landscapes: 3,
    price: 1,
    easeOfEntry: 4,
    food: 5,
    experiences: 7,
    drivers: 4,
    roads: null,
    rating: 4.375,
    returnVisit: "Y",
    reason: "Very expensive, feels like I know it fro",
  },
  {
    name: "Mexico",
    continent: "North America",
    culture: 7,
    entertainment: 7,
    landscapes: 3,
    price: 7,
    easeOfEntry: 10,
    food: 7.5,
    experiences: 5,
    drivers: null,
    roads: null,
    rating: 6.642857143,
    returnVisit: "Y",
    reason: "Only stayed in Guadaljara, feel like the",
  },
  {
    name: "Sweden",
    continent: "Northern Europe",
    culture: 6,
    entertainment: 7,
    landscapes: 4,
    price: 2,
    easeOfEntry: 3,
    food: 5,
    experiences: 9,
    drivers: null,
    roads: null,
    rating: 5.142857143,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Estonia",
    continent: "Northern Europe",
    culture: 7.5,
    entertainment: 5,
    landscapes: 3,
    price: 4,
    easeOfEntry: 10,
    food: 5,
    experiences: 4,
    drivers: null,
    roads: null,
    rating: 5.5,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Fiji",
    continent: "Oceania",
    culture: 5,
    entertainment: 6,
    landscapes: 7,
    price: 5,
    easeOfEntry: 10,
    food: 5,
    experiences: 7,
    drivers: null,
    roads: null,
    rating: 6.428571429,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Philippines",
    continent: "Oceania",
    culture: 5,
    entertainment: 8,
    landscapes: 7.5,
    price: 7,
    easeOfEntry: 10,
    food: 4,
    experiences: 6,
    drivers: null,
    roads: null,
    rating: 6.785714286,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Australia",
    continent: "Oceania",
    culture: 5,
    entertainment: 8,
    landscapes: 7.5,
    price: 3,
    easeOfEntry: 10,
    food: 6,
    experiences: 7,
    drivers: 8,
    roads: 8,
    rating: 6.944444444,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "New Zealand",
    continent: "Oceania",
    culture: 5,
    entertainment: 8,
    landscapes: 9,
    price: 3,
    easeOfEntry: 10,
    food: 5,
    experiences: 8,
    drivers: 8,
    roads: 7,
    rating: 7,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Guyana",
    continent: "South America",
    culture: 3,
    entertainment: 4,
    landscapes: 3,
    price: 7,
    easeOfEntry: 7,
    food: 4,
    experiences: 3,
    drivers: 3,
    roads: 3,
    rating: 4.111111111,
    returnVisit: "M",
    reason: "Dirty and dodgy, might be better now",
  },
  {
    name: "Paraguay",
    continent: "South America",
    culture: 3,
    entertainment: 2,
    landscapes: 2,
    price: 7,
    easeOfEntry: 10,
    food: 4,
    experiences: 1,
    drivers: null,
    roads: null,
    rating: 4.142857143,
    returnVisit: "N",
    reason: "Ciudad del Este is chinatown",
  },
  {
    name: "French Guiana",
    continent: "South America",
    culture: 3,
    entertainment: 2,
    landscapes: 3,
    price: 3,
    easeOfEntry: 10,
    food: 3,
    experiences: 7,
    drivers: 4,
    roads: 5,
    rating: 4.444444444,
    returnVisit: "N",
    reason: "Bouff, space launch was class thoug",
  },
  {
    name: "Uruguay",
    continent: "South America",
    culture: 5,
    entertainment: 4,
    landscapes: 3,
    price: 4,
    easeOfEntry: 10,
    food: 6,
    experiences: 3,
    drivers: 6,
    roads: null,
    rating: 5.125,
    returnVisit: "M",
    reason: "OK, was sick during it though so didn",
  },
  {
    name: "Chile",
    continent: "South America",
    culture: 3,
    entertainment: 4,
    landscapes: 7,
    price: 5,
    easeOfEntry: 10,
    food: 5,
    experiences: 5,
    drivers: null,
    roads: null,
    rating: 5.571428571,
    returnVisit: "Y",
    reason: "Only saw the Atacama",
  },
  {
    name: "Suriname",
    continent: "South America",
    culture: 6,
    entertainment: 5,
    landscapes: 3,
    price: 7,
    easeOfEntry: 7,
    food: 4,
    experiences: 7,
    drivers: null,
    roads: null,
    rating: 5.571428571,
    returnVisit: "N",
    reason: "Had a great time with Lloyd, good fun",
  },
  {
    name: "Colombia",
    continent: "South America",
    culture: 5,
    entertainment: 5,
    landscapes: 5,
    price: 7,
    easeOfEntry: 10,
    food: 4,
    experiences: 4,
    drivers: null,
    roads: null,
    rating: 5.714285714,
    returnVisit: "M",
    reason: "Everyone hyped it up, wasn't half as g",
  },
  {
    name: "Ecuador",
    continent: "South America",
    culture: 5,
    entertainment: 5,
    landscapes: 7.5,
    price: 8,
    easeOfEntry: 10,
    food: 4,
    experiences: 7,
    drivers: 5,
    roads: null,
    rating: 6.4375,
    returnVisit: "Y",
    reason: "Underrated, really full of great things.",
  },
  {
    name: "Peru",
    continent: "South America",
    culture: 6,
    entertainment: 5,
    landscapes: 8,
    price: 7,
    easeOfEntry: 10,
    food: 6,
    experiences: 7,
    drivers: 5,
    roads: null,
    rating: 6.75,
    returnVisit: "M",
    reason: "Grand, a bit dull outside of the mount",
  },
  {
    name: "Argentina",
    continent: "South America",
    culture: 8,
    entertainment: 6,
    landscapes: 7,
    price: 5,
    easeOfEntry: 10,
    food: 7,
    experiences: 8,
    drivers: 6,
    roads: null,
    rating: 7.125,
    returnVisit: "Y",
    reason: "Great, different in all the regions, Bue",
  },
  {
    name: "Brazil",
    continent: "South America",
    culture: 8,
    entertainment: 9,
    landscapes: 8,
    price: 6,
    easeOfEntry: 9,
    food: 7,
    experiences: 8,
    drivers: 6,
    roads: null,
    rating: 7.625,
    returnVisit: "Y",
    reason: "FUll of places I've never heard of that",
  },
  {
    name: "Bangladesh",
    continent: "South Asia",
    culture: 4,
    entertainment: 2,
    landscapes: 3,
    price: 7,
    easeOfEntry: 5,
    food: 3,
    experiences: 3,
    drivers: 2,
    roads: 3,
    rating: 3.555555556,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Maldives",
    continent: "South Asia",
    culture: 2,
    entertainment: 1,
    landscapes: 5,
    price: 3,
    easeOfEntry: 7,
    food: 6,
    experiences: 2,
    drivers: 7,
    roads: 5,
    rating: 4.222222222,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "India",
    continent: "South Asia",
    culture: 8,
    entertainment: 2,
    landscapes: 5,
    price: 5,
    easeOfEntry: 4,
    food: 6,
    experiences: 6,
    drivers: 2,
    roads: 5,
    rating: 4.777777778,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Bhutan",
    continent: "South Asia",
    culture: 8,
    entertainment: 5,
    landscapes: 8,
    price: 4,
    easeOfEntry: 2,
    food: 7,
    experiences: 10,
    drivers: 8,
    roads: 4,
    rating: 6.222222222,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Myanmar",
    continent: "South East Asia",
    culture: 8,
    entertainment: 4,
    landscapes: 7,
    price: 8.5,
    easeOfEntry: 4,
    food: 7,
    experiences: 7,
    drivers: 5,
    roads: 5,
    rating: 6.166666667,
    returnVisit: null,
    reason: "",
  },
  {
    name: "Singapore",
    continent: "South East Asia",
    culture: 4,
    entertainment: 4,
    landscapes: 3,
    price: 2,
    easeOfEntry: 10,
    food: 6,
    experiences: 2,
    drivers: null,
    roads: null,
    rating: 4.428571429,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Malaysia",
    continent: "South East Asia",
    culture: 6,
    entertainment: 4,
    landscapes: 4,
    price: 6,
    easeOfEntry: 10,
    food: 6,
    experiences: 3,
    drivers: 7,
    roads: 8,
    rating: 6,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Cambodia",
    continent: "South East Asia",
    culture: 8,
    entertainment: 9,
    landscapes: 4,
    price: 7,
    easeOfEntry: 10,
    food: 5,
    experiences: 8,
    drivers: 5,
    roads: 5,
    rating: 6.777777778,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Thailand",
    continent: "South East Asia",
    culture: 7.5,
    entertainment: 9,
    landscapes: 7.5,
    price: 6,
    easeOfEntry: 5,
    food: 7,
    experiences: 9,
    drivers: 9,
    roads: 7,
    rating: 7.444444444,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Laos",
    continent: "South East Asia",
    culture: 7.5,
    entertainment: 7,
    landscapes: 7,
    price: 7,
    easeOfEntry: 10,
    food: 7,
    experiences: 8,
    drivers: 2,
    roads: 9,
    rating: 7.166666667,
    returnVisit: "M",
    reason: "",
  },
  {
    name: "Vietnam",
    continent: "South East Asia",
    culture: 7.5,
    entertainment: 9,
    landscapes: 7,
    price: 7,
    easeOfEntry: 5,
    food: 7,
    experiences: 9,
    drivers: 6,
    roads: 7,
    rating: 7.166666667,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Vatican City",
    continent: "Southern Europe",
    culture: 10,
    entertainment: 1,
    landscapes: 1,
    price: 3,
    easeOfEntry: 10,
    food: 5,
    experiences: 7,
    drivers: null,
    roads: null,
    rating: 5.285714286,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Northern Cyprus",
    continent: "Southern Europe",
    culture: 7,
    entertainment: 4,
    landscapes: 6,
    price: 6,
    easeOfEntry: 5,
    food: 6,
    experiences: 6,
    drivers: 7,
    roads: 7,
    rating: 6,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "San Marino",
    continent: "Southern Europe",
    culture: 8,
    entertainment: 5,
    landscapes: 5,
    price: 4,
    easeOfEntry: 10,
    food: 5,
    experiences: 6,
    drivers: null,
    roads: null,
    rating: 6.142857143,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Cyprus",
    continent: "Southern Europe",
    culture: 7.5,
    entertainment: 5,
    landscapes: 6,
    price: 4,
    easeOfEntry: 10,
    food: 6,
    experiences: 6,
    drivers: 7,
    roads: 7,
    rating: 6.5,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Portugal",
    continent: "Southern Europe",
    culture: 8,
    entertainment: 7,
    landscapes: 6,
    price: 5,
    easeOfEntry: 10,
    food: 7,
    experiences: 5,
    drivers: null,
    roads: null,
    rating: 6.857142857,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Italy",
    continent: "Southern Europe",
    culture: 10,
    entertainment: 7,
    landscapes: 7.5,
    price: 5,
    easeOfEntry: 10,
    food: 8,
    experiences: 7.5,
    drivers: 5,
    roads: 7,
    rating: 7.444444444,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Spain",
    continent: "Southern Europe",
    culture: 8,
    entertainment: 8,
    landscapes: 7.5,
    price: 5,
    easeOfEntry: 10,
    food: 7,
    experiences: 8,
    drivers: 8,
    roads: 7,
    rating: 7.611111111,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Greece",
    continent: "Southern Europe",
    culture: 10,
    entertainment: 7,
    landscapes: 7.5,
    price: 5,
    easeOfEntry: 10,
    food: 7.5,
    experiences: 6.5,
    drivers: null,
    roads: null,
    rating: 7.642857143,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Guinea",
    continent: "West Africa",
    culture: 2,
    entertainment: 2,
    landscapes: 3,
    price: 5,
    easeOfEntry: 1,
    food: 4,
    experiences: 8,
    drivers: 3,
    roads: 1,
    rating: 3.222222222,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Senegal",
    continent: "West Africa",
    culture: 3,
    entertainment: 2,
    landscapes: 3,
    price: 5,
    easeOfEntry: 5,
    food: 4,
    experiences: 3,
    drivers: 5,
    roads: 3,
    rating: 3.666666667,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Gambia",
    continent: "West Africa",
    culture: 2,
    entertainment: 3,
    landscapes: 2,
    price: 5,
    easeOfEntry: 5,
    food: 4,
    experiences: 7.5,
    drivers: 5,
    roads: 3,
    rating: 4.055555556,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Guinea Bissau",
    continent: "West Africa",
    culture: 2,
    entertainment: 5,
    landscapes: 6,
    price: 6,
    easeOfEntry: 4,
    food: 4,
    experiences: 7.5,
    drivers: 5,
    roads: 2,
    rating: 4.611111111,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Mauritania",
    continent: "West Africa",
    culture: 2,
    entertainment: 3,
    landscapes: 6,
    price: 6,
    easeOfEntry: 4,
    food: 4,
    experiences: 7.5,
    drivers: 5,
    roads: 4,
    rating: 4.611111111,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Cape Verde",
    continent: "West Africa",
    culture: 4,
    entertainment: 6,
    landscapes: 6.5,
    price: 6,
    easeOfEntry: 5,
    food: 5,
    experiences: 4,
    drivers: 5,
    roads: 5,
    rating: 5.166666667,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Sierra Leone",
    continent: "West Africa",
    culture: 3,
    entertainment: 4,
    landscapes: 7.5,
    price: 6,
    easeOfEntry: 4,
    food: 5,
    experiences: 7.5,
    drivers: 5,
    roads: 5,
    rating: 5.222222222,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Palestine",
    continent: "Western Asia",
    culture: 5,
    entertainment: 2,
    landscapes: 4,
    price: 3,
    easeOfEntry: 5,
    food: 5,
    experiences: 5,
    drivers: null,
    roads: null,
    rating: 4.142857143,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Azerbaijan",
    continent: "Western Asia",
    culture: 3,
    entertainment: 3,
    landscapes: 4,
    price: 6,
    easeOfEntry: 10,
    food: 5,
    experiences: 3,
    drivers: 6,
    roads: 5,
    rating: null,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Armenia",
    continent: "Western Asia",
    culture: 5,
    entertainment: 7,
    landscapes: 5,
    price: 5,
    easeOfEntry: 8,
    food: 6,
    experiences: 7,
    drivers: 4,
    roads: 5,
    rating: 5.777777778,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Turkey",
    continent: "Western Asia",
    culture: 8,
    entertainment: 6.5,
    landscapes: 8,
    price: 7,
    easeOfEntry: 5,
    food: 7,
    experiences: 6,
    drivers: 7,
    roads: 10,
    rating: 7.166666667,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Georgia",
    continent: "Western Asia",
    culture: 8,
    entertainment: 7,
    landscapes: 9,
    price: 5,
    easeOfEntry: 10,
    food: 7.5,
    experiences: 7,
    drivers: 7,
    roads: 6,
    rating: 7.388888889,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Monaco",
    continent: "Western Europe",
    culture: 4,
    entertainment: 3,
    landscapes: 2,
    price: 1,
    easeOfEntry: 10,
    food: 5,
    experiences: 2,
    drivers: null,
    roads: null,
    rating: 3.857142857,
    returnVisit: "N",
    reason: "",
  },
  {
    name: "Belgium",
    continent: "Western Europe",
    culture: 7,
    entertainment: 5,
    landscapes: 2,
    price: 3,
    easeOfEntry: 10,
    food: 5,
    experiences: 4,
    drivers: null,
    roads: null,
    rating: 5.142857143,
    returnVisit: "M",
    reason: "",
  },
  {
    name: "Luxembourg",
    continent: "Western Europe",
    culture: 7,
    entertainment: 3,
    landscapes: 4,
    price: 4,
    easeOfEntry: 10,
    food: 5,
    experiences: 4,
    drivers: null,
    roads: null,
    rating: 5.285714286,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Netherlands",
    continent: "Western Europe",
    culture: 7,
    entertainment: 7,
    landscapes: 2,
    price: 4,
    easeOfEntry: 10,
    food: 5,
    experiences: 7,
    drivers: null,
    roads: null,
    rating: 6,
    returnVisit: "M",
    reason: "",
  },
  {
    name: "UK",
    continent: "Western Europe",
    culture: 6,
    entertainment: 8,
    landscapes: 5,
    price: 3,
    easeOfEntry: 10,
    food: 5,
    experiences: 8,
    drivers: 8,
    roads: 6,
    rating: 6.555555556,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "Ireland",
    continent: "Western Europe",
    culture: 6,
    entertainment: 8,
    landscapes: 5,
    price: 3,
    easeOfEntry: 10,
    food: 5,
    experiences: 8,
    drivers: 9,
    roads: 6,
    rating: 6.666666667,
    returnVisit: "Y",
    reason: "",
  },
  {
    name: "France",
    continent: "Western Europe",
    culture: 8,
    entertainment: 8,
    landscapes: 8,
    price: 3,
    easeOfEntry: 10,
    food: 7.5,
    experiences: 8,
    drivers: 8,
    roads: 6,
    rating: 7.388888889,
    returnVisit: "Y",
    reason: "",
  },
];

export function formatRatingScore(value: number | null, digits = 2): string {
  if (value == null) return "—";
  return value.toLocaleString("en-GB", {
    minimumFractionDigits: Number.isInteger(value) ? 0 : Math.min(digits, 2),
    maximumFractionDigits: digits,
  });
}

export function formatReturnVisit(value: CountryReturnVisit | null): string {
  if (value === "Y") return "Yes";
  if (value === "N") return "No";
  if (value === "M") return "Maybe";
  return "—";
}

/** Normalize Mongo/fixture docs into rating rows for the stats UI. */
export function normalizeCountryRatings(data: unknown[]): CountryRatingRow[] {
  const rows: CountryRatingRow[] = [];
  for (const item of data) {
    if (!item || typeof item !== "object") continue;
    const record = item as Partial<CountryRatingRow>;
    if (typeof record.name !== "string" || !record.name.trim()) continue;
    if (typeof record.continent !== "string" || !record.continent.trim()) {
      continue;
    }
    rows.push({
      name: record.name.trim(),
      continent: record.continent.trim(),
      culture: Number(record.culture) || 0,
      entertainment: Number(record.entertainment) || 0,
      landscapes: Number(record.landscapes) || 0,
      price: Number(record.price) || 0,
      easeOfEntry: Number(record.easeOfEntry) || 0,
      food: Number(record.food) || 0,
      experiences: Number(record.experiences) || 0,
      drivers: record.drivers == null ? null : Number(record.drivers),
      roads: record.roads == null ? null : Number(record.roads),
      rating: null,
      returnVisit:
        record.returnVisit === "Y" ||
        record.returnVisit === "N" ||
        record.returnVisit === "M"
          ? record.returnVisit
          : null,
      reason: typeof record.reason === "string" ? record.reason : "",
    });
  }

  return rows
    .map((row) => ({
      ...row,
      rating: computeCountryRatingAverage(row),
    }))
    .sort((a, b) =>
      a.name.localeCompare(b.name, "en-GB", { sensitivity: "base" }),
    );
}
