export type PassatCountryRow = {
  country: string;
  totalKms: number;
  daysSpent: number;
  tanksFilled: number;
  averagePricePerLitreEur: number;
  dieselSpentEur: number;
  tollsEur: number;
  insuranceEur: number;
  otherEntryFeesEur: number;
  finesEur: number;
  carPartsEur: number;
  totalEur: number;
};

export type PassatBreakdownRow = {
  part: string;
  country: string;
  fixed: boolean;
  priceEur: number;
};

/** Country-by-country costs from the Passat road trip spreadsheet. */
export const PASSAT_COUNTRY_ROWS: PassatCountryRow[] = [
  {
    country: "Ireland",
    totalKms: 422,
    daysSpent: 1,
    tanksFilled: 1,
    averagePricePerLitreEur: 1.7,
    dieselSpentEur: 80,
    tollsEur: 6.6,
    insuranceEur: 550,
    otherEntryFeesEur: 0,
    finesEur: 0,
    carPartsEur: 20,
    totalEur: 656.6,
  },
  {
    country: "France",
    totalKms: 843,
    daysSpent: 2,
    tanksFilled: 1,
    averagePricePerLitreEur: 1.66,
    dieselSpentEur: 52.95,
    tollsEur: 53.5,
    insuranceEur: 0,
    otherEntryFeesEur: 220,
    finesEur: 0,
    carPartsEur: 0,
    totalEur: 326.45,
  },
  {
    country: "Germany",
    totalKms: 625,
    daysSpent: 1,
    tanksFilled: 1,
    averagePricePerLitreEur: 1.62,
    dieselSpentEur: 100,
    tollsEur: 0,
    insuranceEur: 0,
    otherEntryFeesEur: 0,
    finesEur: 0,
    carPartsEur: 0,
    totalEur: 100,
  },
  {
    country: "Austria",
    totalKms: 344,
    daysSpent: 2,
    tanksFilled: 1,
    averagePricePerLitreEur: 1.56,
    dieselSpentEur: 100,
    tollsEur: 17.87,
    insuranceEur: 0,
    otherEntryFeesEur: 0,
    finesEur: 300,
    carPartsEur: 0,
    totalEur: 417.87,
  },
  {
    country: "Hungary",
    totalKms: 463,
    daysSpent: 1,
    tanksFilled: 0,
    averagePricePerLitreEur: 1.57,
    dieselSpentEur: 0,
    tollsEur: 9.3,
    insuranceEur: 0,
    otherEntryFeesEur: 0,
    finesEur: 0,
    carPartsEur: 0,
    totalEur: 9.3,
  },
  {
    country: "Romania",
    totalKms: 1419,
    daysSpent: 15,
    tanksFilled: 2,
    averagePricePerLitreEur: 1.55,
    dieselSpentEur: 89.71,
    tollsEur: 12,
    insuranceEur: 0,
    otherEntryFeesEur: 0,
    finesEur: 0,
    carPartsEur: 0,
    totalEur: 101.71,
  },
  {
    country: "Bulgaria",
    totalKms: 371,
    daysSpent: 1,
    tanksFilled: 0,
    averagePricePerLitreEur: 1.25,
    dieselSpentEur: 100,
    tollsEur: 5.5,
    insuranceEur: 0,
    otherEntryFeesEur: 0,
    finesEur: 0,
    carPartsEur: 0,
    totalEur: 105.5,
  },
  {
    country: "Turkey",
    totalKms: 1881,
    daysSpent: 5,
    tanksFilled: 3,
    averagePricePerLitreEur: 1.16,
    dieselSpentEur: 186,
    tollsEur: 27.02,
    insuranceEur: 30,
    otherEntryFeesEur: 0,
    finesEur: 0,
    carPartsEur: 0,
    totalEur: 243.02,
  },
  {
    country: "Georgia",
    totalKms: 1827,
    daysSpent: 7,
    tanksFilled: 4,
    averagePricePerLitreEur: 0.96,
    dieselSpentEur: 154,
    tollsEur: 0,
    insuranceEur: 9.9,
    otherEntryFeesEur: 100,
    finesEur: 300,
    carPartsEur: 50,
    totalEur: 613.9,
  },
  {
    country: "Armenia",
    totalKms: 1042,
    daysSpent: 5,
    tanksFilled: 0,
    averagePricePerLitreEur: 1.13,
    dieselSpentEur: 0,
    tollsEur: 0,
    insuranceEur: 5,
    otherEntryFeesEur: 14,
    finesEur: 0,
    carPartsEur: 0,
    totalEur: 19,
  },
  {
    country: "Iran",
    totalKms: 804,
    daysSpent: 2,
    tanksFilled: 1,
    averagePricePerLitreEur: 0.005,
    dieselSpentEur: 4,
    tollsEur: 0,
    insuranceEur: 0,
    otherEntryFeesEur: 660,
    finesEur: 0,
    carPartsEur: 0,
    totalEur: 664,
  },
  {
    country: "Russia",
    totalKms: 881,
    daysSpent: 3,
    tanksFilled: 1,
    averagePricePerLitreEur: 0.83,
    dieselSpentEur: 60,
    tollsEur: 5,
    insuranceEur: 20,
    otherEntryFeesEur: 77,
    finesEur: 0,
    carPartsEur: 0,
    totalEur: 162,
  },
  {
    country: "Kazakhstan",
    totalKms: 6138,
    daysSpent: 18,
    tanksFilled: 6,
    averagePricePerLitreEur: 0.49,
    dieselSpentEur: 140.7,
    tollsEur: 12.1,
    insuranceEur: 30,
    otherEntryFeesEur: 0,
    finesEur: 0,
    carPartsEur: 47,
    totalEur: 229.8,
  },
  {
    country: "Uzbekistan",
    totalKms: 3419,
    daysSpent: 18,
    tanksFilled: 4,
    averagePricePerLitreEur: 0.8,
    dieselSpentEur: 138.3,
    tollsEur: 5,
    insuranceEur: 3.5,
    otherEntryFeesEur: 0,
    finesEur: 20,
    carPartsEur: 100,
    totalEur: 266.8,
  },
  {
    country: "Kyrgyzstan",
    totalKms: 1058,
    daysSpent: 7,
    tanksFilled: 1,
    averagePricePerLitreEur: 0.79,
    dieselSpentEur: 40,
    tollsEur: 4,
    insuranceEur: 10,
    otherEntryFeesEur: 2,
    finesEur: 0,
    carPartsEur: 0,
    totalEur: 56,
  },
  {
    country: "Kazakhstan 2",
    totalKms: 650,
    daysSpent: 9,
    tanksFilled: 2,
    averagePricePerLitreEur: 0.65,
    dieselSpentEur: 50,
    tollsEur: 1,
    insuranceEur: 7,
    otherEntryFeesEur: 0,
    finesEur: 0,
    carPartsEur: 60,
    totalEur: 118,
  },
  {
    country: "China",
    totalKms: 5370,
    daysSpent: 18,
    tanksFilled: 4,
    averagePricePerLitreEur: 1.03,
    dieselSpentEur: 226.17,
    tollsEur: 180.84,
    insuranceEur: 0,
    otherEntryFeesEur: 1850,
    finesEur: 0,
    carPartsEur: 107,
    totalEur: 2364.01,
  },
  {
    country: "Laos",
    totalKms: 645,
    daysSpent: 5,
    tanksFilled: 0,
    averagePricePerLitreEur: 1.9,
    dieselSpentEur: 0,
    tollsEur: 6.5,
    insuranceEur: 13,
    otherEntryFeesEur: 8,
    finesEur: 0,
    carPartsEur: 0,
    totalEur: 27.5,
  },
  {
    country: "Thailand",
    totalKms: 2020,
    daysSpent: 11,
    tanksFilled: 2,
    averagePricePerLitreEur: 1.1,
    dieselSpentEur: 80,
    tollsEur: 14,
    insuranceEur: 0,
    otherEntryFeesEur: 300,
    finesEur: 0,
    carPartsEur: 0,
    totalEur: 394,
  },
  {
    country: "Malaysia",
    totalKms: 545,
    daysSpent: 2,
    tanksFilled: 0,
    averagePricePerLitreEur: 1,
    dieselSpentEur: 20,
    tollsEur: 12,
    insuranceEur: 20,
    otherEntryFeesEur: 0,
    finesEur: 0,
    carPartsEur: 0,
    totalEur: 52,
  },
];

export const PASSAT_COUNTRY_TOTALS: PassatCountryRow = {
  country: "Total",
  totalKms: 30767,
  daysSpent: 133,
  tanksFilled: 34,
  averagePricePerLitreEur: 1.13775,
  dieselSpentEur: 1621.83,
  tollsEur: 372.23,
  insuranceEur: 698.4,
  otherEntryFeesEur: 3231,
  finesEur: 620,
  carPartsEur: 384,
  totalEur: 6927.46,
};

export const PASSAT_AMOUNTS_TO_ADD = {
  dieselEur: 61.02,
  tollsEur: [65.48, 34.17] as const,
};

export const PASSAT_BREAKDOWN_ROWS: PassatBreakdownRow[] = [
  { part: "Dipped Headlights", country: "Ireland", fixed: false, priceEur: 0 },
  { part: "Air con", country: "Ireland", fixed: false, priceEur: 0 },
  { part: "Doors not locking", country: "Ireland", fixed: false, priceEur: 0 },
  {
    part: "Suspension/Chassis rumbling",
    country: "Ireland",
    fixed: false,
    priceEur: 0,
  },
  { part: "5th gear slipping", country: "Ireland", fixed: false, priceEur: 0 },
  { part: "Oil change", country: "Ireland", fixed: true, priceEur: 20 },
  { part: "Boot mechanism", country: "Iran", fixed: true, priceEur: 0 },
  { part: "Battery robbed", country: "Georgia", fixed: true, priceEur: 50 },
  {
    part: "Accelerator Squeeling",
    country: "Kazakhstan",
    fixed: true,
    priceEur: 0,
  },
  { part: "Battery Flat", country: "Kazakhstan", fixed: true, priceEur: 47 },
  {
    part: "Bonnet cable broken",
    country: "Kazakhstan",
    fixed: false,
    priceEur: 0,
  },
  {
    part: "Washer Fluid Pipe",
    country: "Kazakhstan",
    fixed: false,
    priceEur: 0,
  },
  { part: "Turbo breaking", country: "Uzbekistan", fixed: true, priceEur: 14.2 },
  { part: "Oil change", country: "Uzbekistan", fixed: true, priceEur: 46.86 },
  { part: "Oil change", country: "Uzbekistan", fixed: true, priceEur: 51.12 },
  {
    part: "Brake pedal stuck",
    country: "Kazakhstan",
    fixed: true,
    priceEur: 60,
  },
  { part: "Turbo and Aircon", country: "China", fixed: false, priceEur: 94 },
  { part: "Air filter", country: "China", fixed: true, priceEur: 13 },
  {
    part: "Front Passenger Door",
    country: "China",
    fixed: true,
    priceEur: 0,
  },
];

export const PASSAT_BREAKDOWN_TOTAL_EUR = 396.18;

export function formatPassatEur(value: number): string {
  return value.toLocaleString("en-GB", {
    style: "currency",
    currency: "EUR",
    minimumFractionDigits: value % 1 === 0 ? 0 : 2,
    maximumFractionDigits: 2,
  });
}

export function formatPassatNumber(value: number, digits = 0): string {
  return value.toLocaleString("en-GB", {
    minimumFractionDigits: digits,
    maximumFractionDigits: digits,
  });
}
